"""Pydantic models for TensorStore specifications.

This package provides type-safe, validated models for TensorStore specifications,
built with Pydantic v2 for excellent IDE support and runtime validation.

Example:
    >>> from pydantic_tensorstore import validate_spec
    >>> spec = validate_spec(
    ...     {"driver": "array", "array": [[1, 2], [3, 4]], "dtype": "float32"}
    ... )
    >>> print(spec.driver)
    array
"""

from importlib.metadata import PackageNotFoundError, version

try:
    __version__ = version("pydantic-tensorstore")
except PackageNotFoundError:  # pragma: no cover
    __version__ = "0.0.0"

from pydantic_tensorstore._core.base import (
    MIN_TENSORSTORE_VERSION,
    TensorStoreModel,
    UnsupportedTensorStoreVersionError,
    installed_tensorstore_version,
    since,
    since_inline,
)
from pydantic_tensorstore._core.chunk_layout import ChunkLayout, ChunkLayoutGrid
from pydantic_tensorstore._core.codec import CodecBase
from pydantic_tensorstore._core.context import (
    AwsCredentials,
    AwsCredentialsAnonymous,
    AwsCredentialsDefault,
    AwsCredentialsEcs,
    AwsCredentialsEnvironment,
    AwsCredentialsImds,
    AwsCredentialsProfile,
    CachePool,
    Context,
    DataCopyConcurrency,
    FileIOConcurrency,
    FileIOLocking,
    FileIOMode,
    GCSUserProject,
    HTTPRequestConcurrency,
    MemoryKeyValueStore,
    OcdbtCoordinator,
    RateLimiter,
    RequestRetries,
)
from pydantic_tensorstore._core.schema import Schema
from pydantic_tensorstore._core.spec import (
    BaseSpec,
    CacheRevalidationBound,
    ChunkedTensorStoreKvStoreAdapterSpec,
    TensorStoreAdapterSpec,
    TensorStoreKvStoreAdapterSpec,
)
from pydantic_tensorstore._core.transform import (
    ImplicitBound,
    IndexDomain,
    IndexInterval,
    IndexTransform,
    IntOrInf,
    OutputIndexMap,
)
from pydantic_tensorstore._drivers import Codec, TensorStoreSpec
from pydantic_tensorstore._drivers.array import ArraySpec
from pydantic_tensorstore._drivers.auto import AutoSpec
from pydantic_tensorstore._drivers.cast import CastSpec
from pydantic_tensorstore._drivers.downsample import DownsampleMethod, DownsampleSpec
from pydantic_tensorstore._drivers.image import (
    AvifSpec,
    BmpSpec,
    JpegSpec,
    PngSpec,
    TiffSpec,
    WebpSpec,
)
from pydantic_tensorstore._drivers.json import JsonSpec
from pydantic_tensorstore._drivers.n5 import (
    VALID_N5_DTYPES,
    N5Codec,
    N5Compression,
    N5CompressionBlosc,
    N5CompressionBzip2,
    N5CompressionGzip,
    N5CompressionRaw,
    N5CompressionXZ,
    N5CompressionZstd,
    N5DataType,
    N5Metadata,
    N5Spec,
)
from pydantic_tensorstore._drivers.neuroglancer_precomputed import (
    VALID_NEUROGLANCER_DTYPES,
    NeuroglancerDataType,
    NeuroglancerEncoding,
    NeuroglancerMultiscaleMetadata,
    NeuroglancerPrecomputedCodec,
    NeuroglancerPrecomputedSpec,
    NeuroglancerScaleMetadata,
)
from pydantic_tensorstore._drivers.stack import StackSpec
from pydantic_tensorstore._drivers.zarr import (
    Zarr2Codec,
    Zarr2Compressor,
    Zarr2CompressorBlosc,
    Zarr2CompressorBz2,
    Zarr2CompressorZlib,
    Zarr2CompressorZstd,
    Zarr2DataType,
    Zarr2Metadata,
    Zarr2SimpleDataType,
    Zarr2Spec,
    Zarr2StructuredDataType,
)
from pydantic_tensorstore._drivers.zarr3 import (
    VALID_ZARR3_DTYPES,
    Zarr3Attributes,
    Zarr3BloscConfig,
    Zarr3BytesConfig,
    Zarr3ChunkConfiguration,
    Zarr3ChunkGrid,
    Zarr3ChunkKeyEncoding,
    Zarr3ChunkKeyEncodingConfig,
    Zarr3ChunkKeyEncodingDefault,
    Zarr3ChunkKeyEncodingV2,
    Zarr3Codec,
    Zarr3CodecBlosc,
    Zarr3CodecBytes,
    Zarr3CodecChain,
    Zarr3CodecCRC32C,
    Zarr3CodecGzip,
    Zarr3CodecShardingIndexed,
    Zarr3CodecTranspose,
    Zarr3CodecZstd,
    Zarr3CRC32CConfig,
    Zarr3DataType,
    Zarr3GzipConfig,
    Zarr3Metadata,
    Zarr3ShardingIndexedConfig,
    Zarr3SingleCodec,
    Zarr3Spec,
    Zarr3TransposeConfig,
    Zarr3ZstdConfig,
)
from pydantic_tensorstore._kvstore import (
    BaseKvStore,
    FileKvStore,
    GCSKvStore,
    HTTPKvStore,
    KvStackKvStore,
    KvStackLayer,
    KvStore,
    KvStoreAdapter,
    KvStoreUrl,
    MemoryKvStore,
    NeuroglancerShardingSpec,
    NeuroglancerUint64ShardedKvStore,
    OcdbtConfig,
    OcdbtKvStore,
    OcdbtZstdCompression,
    S3KvStore,
    TsGrpcKvStore,
    Zarr3ShardingIndexedKvStore,
    ZipKvStore,
)
from pydantic_tensorstore._types import (
    DTYPE_SINCE,
    ContextResource,
    ContextResourceName,
    DataType,
    DriverName,
    OpenMode,
    ReadWriteMode,
    Unit,
)
from pydantic_tensorstore._validators import validate_kvstore, validate_spec

TENSORSTORE_VERSION = "0.1.85"
"""The tensorstore release whose JSON schema these models were verified against.

Specs also work with older releases down to `MIN_TENSORSTORE_VERSION` as long as
they avoid newer features; `spec.required_tensorstore_version()` reports the oldest
release a given spec needs, and `to_tensorstore()` checks it before calling
tensorstore.
"""

__all__ = [
    "DTYPE_SINCE",
    "MIN_TENSORSTORE_VERSION",
    "TENSORSTORE_VERSION",
    "VALID_N5_DTYPES",
    "VALID_NEUROGLANCER_DTYPES",
    "VALID_ZARR3_DTYPES",
    "ArraySpec",
    "AutoSpec",
    "AvifSpec",
    "AwsCredentials",
    "AwsCredentialsAnonymous",
    "AwsCredentialsDefault",
    "AwsCredentialsEcs",
    "AwsCredentialsEnvironment",
    "AwsCredentialsImds",
    "AwsCredentialsProfile",
    "BaseKvStore",
    "BaseSpec",
    "BmpSpec",
    "CachePool",
    "CacheRevalidationBound",
    "CastSpec",
    "ChunkLayout",
    "ChunkLayoutGrid",
    "ChunkedTensorStoreKvStoreAdapterSpec",
    "Codec",
    "CodecBase",
    "Context",
    "ContextResource",
    "ContextResourceName",
    "DataCopyConcurrency",
    "DataType",
    "DownsampleMethod",
    "DownsampleSpec",
    "DriverName",
    "FileIOConcurrency",
    "FileIOLocking",
    "FileIOMode",
    "FileKvStore",
    "GCSKvStore",
    "GCSUserProject",
    "HTTPKvStore",
    "HTTPRequestConcurrency",
    "ImplicitBound",
    "IndexDomain",
    "IndexInterval",
    "IndexTransform",
    "IntOrInf",
    "JpegSpec",
    "JsonSpec",
    "KvStackKvStore",
    "KvStackLayer",
    "KvStore",
    "KvStoreAdapter",
    "KvStoreUrl",
    "MemoryKeyValueStore",
    "MemoryKvStore",
    "N5Codec",
    "N5Compression",
    "N5CompressionBlosc",
    "N5CompressionBzip2",
    "N5CompressionGzip",
    "N5CompressionRaw",
    "N5CompressionXZ",
    "N5CompressionZstd",
    "N5DataType",
    "N5Metadata",
    "N5Spec",
    "NeuroglancerDataType",
    "NeuroglancerEncoding",
    "NeuroglancerMultiscaleMetadata",
    "NeuroglancerPrecomputedCodec",
    "NeuroglancerPrecomputedSpec",
    "NeuroglancerScaleMetadata",
    "NeuroglancerShardingSpec",
    "NeuroglancerUint64ShardedKvStore",
    "OcdbtConfig",
    "OcdbtCoordinator",
    "OcdbtKvStore",
    "OcdbtZstdCompression",
    "OpenMode",
    "OutputIndexMap",
    "PngSpec",
    "RateLimiter",
    "ReadWriteMode",
    "RequestRetries",
    "S3KvStore",
    "Schema",
    "StackSpec",
    "TensorStoreAdapterSpec",
    "TensorStoreKvStoreAdapterSpec",
    "TensorStoreModel",
    "TensorStoreSpec",
    "TiffSpec",
    "TsGrpcKvStore",
    "Unit",
    "UnsupportedTensorStoreVersionError",
    "WebpSpec",
    "Zarr2Codec",
    "Zarr2Compressor",
    "Zarr2CompressorBlosc",
    "Zarr2CompressorBz2",
    "Zarr2CompressorZlib",
    "Zarr2CompressorZstd",
    "Zarr2DataType",
    "Zarr2Metadata",
    "Zarr2SimpleDataType",
    "Zarr2Spec",
    "Zarr2StructuredDataType",
    "Zarr3Attributes",
    "Zarr3BloscConfig",
    "Zarr3BytesConfig",
    "Zarr3CRC32CConfig",
    "Zarr3ChunkConfiguration",
    "Zarr3ChunkGrid",
    "Zarr3ChunkKeyEncoding",
    "Zarr3ChunkKeyEncodingConfig",
    "Zarr3ChunkKeyEncodingDefault",
    "Zarr3ChunkKeyEncodingV2",
    "Zarr3Codec",
    "Zarr3CodecBlosc",
    "Zarr3CodecBytes",
    "Zarr3CodecCRC32C",
    "Zarr3CodecChain",
    "Zarr3CodecGzip",
    "Zarr3CodecShardingIndexed",
    "Zarr3CodecTranspose",
    "Zarr3CodecZstd",
    "Zarr3DataType",
    "Zarr3GzipConfig",
    "Zarr3Metadata",
    "Zarr3ShardingIndexedConfig",
    "Zarr3ShardingIndexedKvStore",
    "Zarr3SingleCodec",
    "Zarr3Spec",
    "Zarr3TransposeConfig",
    "Zarr3ZstdConfig",
    "ZipKvStore",
    "installed_tensorstore_version",
    "since",
    "since_inline",
    "validate_kvstore",
    "validate_spec",
]
